function get_terms(lot){
  var tc = document.getElementById('terms_conditions');
  switch(lot) {
  case '':
    tc.innerHTML = '* Please select your Lot Size to view the Terms and Conditions that apply to you. Thank you.';
    break;
  case '1':
    tc.innerHTML = '* All gates and areas to be aerated must be wide enough to accommodate our machines. Excludes areas on steep hills and where shallow roots are present. Service is for areas of viable turf. All lawn sprinkler heads (on OR ADJACENT to your property) and ambiguous or abnormally shaped property lines MUST BE CLEARLY MARKED WITH PIN FLAGS, which can be purchased at your local Home Improvement Store. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags. Areas adjacent to, but not part of your property (such as public parkland and common grounds) may cost extra. Payment shall become due upon completion of work. You will be given the option to pay online. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service. A $35.00 fee shall apply to each returned check. Invoices are emailed (CHECK YOUR SPAM FILTER if you do not receive it within 2 days) but MAY be mailed via USPS or delivered at time of service. We reserve the right to refuse any job.';
    break;
  case '2':
    tc.innerHTML = '* All gates and areas to be aerated must be wide enough to accommodate our machines. Excludes areas on steep hills and where shallow roots are present. Service is for areas of viable turf. All lawn sprinkler heads (on OR ADJACENT to your property) and ambiguous or abnormally shaped property lines MUST BE CLEARLY MARKED WITH PIN FLAGS, which can be purchased at your local Home Improvement Store. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags. Areas adjacent to, but not part of your property (such as public parkland and common grounds) may cost extra. Payment shall become due upon completion of work. You will be given the option to pay online. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service. A $35.00 fee shall apply to each returned check. Invoices are emailed (CHECK YOUR SPAM FILTER if you do not receive it within 2 days) but MAY be mailed via USPS or delivered at time of service. We reserve the right to refuse any job.';
    break;
  case '3':
    tc.innerHTML = '* All gates and areas to be aerated must be wide enough to accommodate our machines. Excludes areas on steep hills and where shallow roots are present. Service is for areas of viable turf. All lawn sprinkler heads (on OR ADJACENT to your property) and ambiguous or abnormally shaped property lines MUST BE CLEARLY MARKED WITH PIN FLAGS, which can be purchased at your local Home Improvement Store. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags. Areas adjacent to, but not part of your property (such as public parkland and common grounds) may cost extra. Payment shall become due upon completion of work. You will be given the option to pay online. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service. A $35.00 fee shall apply to each returned check. Invoices are emailed (CHECK YOUR SPAM FILTER if you do not receive it within 2 days) but MAY be mailed via USPS or delivered at time of service. We reserve the right to refuse any job.';
    break;
  case '4':
    tc.innerHTML = '* All gates and areas to be aerated must be wide enough to accommodate our machines. Excludes areas on steep hills and where shallow roots are present. Service is for areas of viable turf. All lawn sprinkler heads (on OR ADJACENT to your property) and ambiguous or abnormally shaped property lines MUST BE CLEARLY MARKED WITH PIN FLAGS, which can be purchased at your local Home Improvement Store. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags. Areas adjacent to, but not part of your property (such as public parkland and common grounds) may cost extra. Payment shall become due upon completion of work. You will be given the option to pay online. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service. A $35.00 fee shall apply to each returned check. Invoices are emailed (CHECK YOUR SPAM FILTER if you do not receive it within 2 days) but MAY be mailed via USPS or delivered at time of service. We reserve the right to refuse any job.';
    break;
  case '5':
    tc.innerHTML = '* All gates and areas to be aerated must be wide enough to accommodate our machines. Excludes areas on steep hills and where shallow roots are present. Service is for areas of viable turf. All lawn sprinkler heads (on OR ADJACENT to your property) and ambiguous or abnormally shaped property lines MUST BE CLEARLY MARKED WITH PIN FLAGS, which can be purchased at your local Home Improvement Store. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags. Areas adjacent to, but not part of your property (such as public parkland and common grounds) may cost extra. Payment shall become due upon completion of work. You will be given the option to pay online. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service. A $35.00 fee shall apply to each returned check. Invoices are emailed (CHECK YOUR SPAM FILTER if you do not receive it within 2 days) but MAY be mailed via USPS or delivered at time of service. We reserve the right to refuse any job.';
    break;
  case '6':
    tc.innerHTML = '* All gates and areas to be aerated must be wide enough to accommodate our machines. Excludes areas on steep hills and where shallow roots are present. Service is for areas of viable turf. All lawn sprinkler heads (on OR ADJACENT to your property) and ambiguous or abnormally shaped property lines MUST BE CLEARLY MARKED WITH PIN FLAGS, which can be purchased at your local Home Improvement Store. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags. Areas adjacent to, but not part of your property (such as public parkland and common grounds) may cost extra. Payment shall become due upon completion of work. You will be given the option to pay online. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service. A $35.00 fee shall apply to each returned check. Invoices are emailed (CHECK YOUR SPAM FILTER if you do not receive it within 2 days) but MAY be mailed via USPS or delivered at time of service. We reserve the right to refuse any job.';
    break;
  case '7':
    tc.innerHTML = '*All gates and areas to be aerated must be wide enough to accommodate our equipment. Excludes areas on steep hills or where shallow roots are present. Price is for Open Areas properties. All areas we define as “Open Areas” must be LAWN AREAS (as opposed to meadow/pasture) safely accessible by our tractor and tow-behind aerator AND must have minimal areas that are only accessible by our walk-behind machines. Different prices may apply to properties that are mostly accessible only by our walk-behind units. ALL AREAS TO BE AERATED (whether by tractor or walk-behind unit) MUST BE CLEARLY DEFINED WITH PIN FLAGS (unless otherwise defined by fences) AND must be safely accessible by our equipment. If no one is home at time of service, we will service only the unmarked turf areas that we deem to be your property.'+
                   '<br><br>Price Quote is valid for lot sizes—at our discretion—that are 2-5 acres in total size and that are within our Service Area. Quoted price INCLUDES footprint of house, driveway, landscaping, etc. If a SIGNIFICANT PORTION of your lot is comprised of non-turf areas (20% or more being woods, landscaping, pasture, etc.) THEN YOU MUST REQUEST A SEPARATE QUOTE WHEN YOU SIGN UP FOR SERVICE; OTHERWISE, QUOTED PRICE SHALL APPLY TO YOUR LAWN. ADDITIONALLY, IF YOU WISH US TO SERVICE ONLY A PORTION OF YOUR PROPERTY, YOU MUST REQUEST THIS WHEN YOU SIGN UP FOR SERVICE. We will plan to service all accessible turf areas of your property. Servicing areas adjacent to, but not part of your property (such as common grounds and public parkland) may cost extra.'+
                   '<br><br>All lawn sprinkler heads (yours AND NEIGHBORS OF YOURS) AND ANYTHING ELSE THAT MAY NOT BE EASILY SEEN MUST BE MARKED WITH PIN FLAGS. We will not be responsible for damage to any sprinkler head, pipe, wire, cable or other utility or anything else that is not marked with Pin Flags.'+
                   '<br><br>Service is for areas of viable turf. Payment shall become due upon completion of work. You will be given the option to pay online with your credit card. Late fees of $5.00 per day (retroactive to date of service) shall apply to Invoices not paid within 10 days of service.'+
                   '<br><br>To opt for our 3-for-3 Payment Plan, you must give your valid credit card information to The Aeration Corps to keep on file (a SECURE page will display once you click the "Save" button). Your first payment will be charged after completion of work. Your second and third payments will be charged 30 and 60 days, respectively, from your first payment. Due to typical payment amounts, YOU MAY NEED TO CONTACT YOUR CREDIT CARD COMPANY TO AUTHORIZE THE AERATION CORPS TO CHARGE YOUR CARD. IN SUCH CASE, YOU AGREE TO MAKE ALL NECESSARY ARRANGEMENTS WITH YOUR CREDIT CARD COMPANY PROMPTLY SO AS TO ALLOW FOR A STREAMLINED PAYMENT PROCESS. FURTHERMORE, YOU AGREE THAT OUR LATE FEES (detailed in the paragraph above) MAY APPLY TO ANY OF YOUR THREE INVOICES IF WE EXPERIENCE DIFFICULTY CHARGING YOUR CREDIT CARD THAT RESULTS FROM PROBLEMS WITH YOUR CREDIT CARD COMPANY AND/OR ANY OTHER ISSUE THAT REQUIRES YOUR ATTENTION.'+
                   '<br><br>A $35.00 fee shall apply to each returned check. Price Quote is based upon Public Information. If your property size is different than what is recorded with the County, then Price Quote may become null and void at our discretion. We reserve the right to refuse any job.';
    break;
  default:
    tc.innerHTML = '* ERROR: Lot size not recognized...';
}
}